name: CI/CD project
on: 
  workflow_dispatch: # Putting here is also fine!!
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  integrations_project:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install mocha global
        run: npm install -g mocha
      - name: install npm modules
        run: npm install
      - name: testing project
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deloy nprTennisService on server
      uses: appleboy/ssh-action@master # An action made to control Linux servers
      with: # We set all our secrets here for the action, these won't be shown in the action logs
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd ../
            cd home/nprTennisService # we move into our app's folder
            git pull # we pull any changes from git
            npm install # we install any missing dependencies
            npm run build # we build our app
            pm2 reload all # we reload the app via PM2
